workspace:
  base: /go
  path: src/github.com/journeymidnight/lsblk-crow
pipeline:
  build:
    image: centos:7.2.1511
    commands:
      #go
      - yum install -y git
      - yum install -y rpm-build make cmake gcc gcc-c++
      - yum install -y libmount-devel boost-devel systemd-devel boost-static
      - bash package/rpmbuild.sh
  github_release:
    image: plugins/github-release
    files:
      - "serve-blk*.rpm"
    checksum:
      - md5
    secrets: [github_token]
    when:
       event: [tag]
  s3:
    image: plugins/s3
    bucket: jmdrepo
    source: "serve-blk*.rpm"
    secrets: [AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY]
    path_style: false
    acl: public-read
    endpoint: https://oss-cn-beijing.aliyuncs.com
    when:
       event: [tag]
  pushbear:
    image: thesues/drone-pushbear
    url: XXXX
    secrets: [sendkey]
    when:
      event: [tag, push]
      success: false
      failure: false
      change: true
